apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: ""  # Will be filled if using IAM roles for service accounts
